services:
  tanzeksp.server:
    image: ${DOCKER_REGISTRY-}tanzekspserver
    build:
      context: .
      dockerfile: TanzEksp/Server/Dockerfile
    ports: 
    - "8080:8080" ## Http
    - "443:443"   ## Https


