services:
  tanzeksp.server:
    image: ${DOCKER_REGISTRY-}tanzekspserver
    build:
      context: .
      dockerfile: TanzEksp/Server/Dockerfile
    ports:
        - "9597:9597"
    environment:
     ASPNETCORE_HTTP_PORTS: 9597