version: '3.8'

services:
  tanzeksp.server:
    image: ${DOCKER_REGISTRY-}tanzekspserver
    build:
      context: .
      dockerfile: TanzEksp/Server/Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
