name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login ${{ secrets.PMAK-681db31a25de4f00016639b3-2e998ecd2f850ae4d301c1de1d37267226PMAK-681db31a25de4f00016639b3-2e998ecd2f850ae4d301c1de1d37267226 }}
      - name: Run API tests
        run: |
          postman collection run "39520780-9faae00f-b9dc-4b40-8687-825fcb4098df"
