name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.PMAK-681db6a0e059c20001a636fe-9b5e43060a9b8bd8c5fc452a47528a799a }}
      - name: Run API tests
        run: |
          postman collection run "39520780-9faae00f-b9dc-4b40-8687-825fcb4098df"
